language: cpp
compiler:
    - gcc
    - clang

before_install:
    - sudo apt update -y
    # Install Eigen3
    - git clone https://github.com/eigenteam/eigen-git-mirror.git
    - cd eigen-git-mirror/
    - mkdir build
    - cd build
    - cmake ..
    - sudo make install
    - cd ./../..

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - sudo make install
    - ctest -V


